version: 0.0.1.{build}

image: Visual Studio 2015

environment:
  QTDIR: C:\Qt\5.10.1\msvc2015
  ENV_MSVC_PLATFORM: x86
  BUILD_DIR: c:\projects\build
  DIST_DIR: c:\projects\dist
  VSVER: 14.0
  PUSC_VERSION: 1.0.1

configuration:
  - Release

init:
  - cmd: git config --global core.autocrlf true

install:
  - cmd: pip install cram

before_build:
  - cmd: '%QTDIR%\bin\qtenv2.bat'
  - cmd: '"%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ENV_MSVC_PLATFORM%'

build_script:
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  - cmd: qmake %APPVEYOR_BUILD_FOLDER%/maltester.pro -r "CONFIG+=%configuration%"
  - cmd: nmake.exe
  - cmd: "%BUILD_DIR%/src/tests/release/tests.exe"
  - cmd: SET PATH=%BUILD_DIR%\src\app\release;%PATH%
  - cmd: FOR %%t IN ("%APPVEYOR_BUILD_FOLDER%\tests\*.t") DO python -m cram -v -E -y --shell="C:\Program Files\Git\bin\sh.exe" %%t
