version: 0.0.1.{build}

image: Visual Studio 2015

environment:
  QTDIR: C:\Qt\5.9\msvc2015
  ENV_MSVC_PLATFORM: x86
  BUILD_DIR: c:\projects\build
  DIST_DIR: c:\projects\dist
  VSVER: 14.0
  PUSC_VERSION: 1.0.1

configuration:
  - Release

before_build:
  - cmd: '%QTDIR%\bin\qtenv2.bat'
  - cmd: '"%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ENV_MSVC_PLATFORM%'

build_script:
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  - cmd: qmake %APPVEYOR_BUILD_FOLDER%/maltester.pro -r "CONFIG+=%configuration%"
  - cmd: nmake.exe
  - cmd: "%BUILD_DIR%/src/tests/release/tests.exe"
