version: 0.2.{build}

image: Visual Studio 2015

clone_folder: c:\projects\asn1scc.MalTester\src

environment:
  QTDIR: C:\Qt\5.10.1\msvc2015
  ENV_MSVC_PLATFORM: x86
  BUILD_DIR: c:\projects\asn1scc.MalTester\build
  DIST_DIR: c:\projects\asn1scc.MalTester\dist
  DOWNLOAD_DIR: c:\projects\asn1scc.MalTester\downloads
  VSVER: 14.0

configuration:
  - Release

init:
  - cmd: git config --global core.autocrlf true

install:
  - cmd: pip install cram
  - cmd: mkdir %DOWNLOAD_DIR%
  - cmd: curl -fsSL "https://drive.google.com/uc?export=download&id=1tzZdsXU4CHbppf4TQMrkNx-6p0zsCuEt" -o %DOWNLOAD_DIR%\asn1scc.7z
  - cmd: 7z x -y "%DOWNLOAD_DIR%\asn1scc.7z" -o"%DOWNLOAD_DIR%" | findstr /b /r /c:"\<Everything is Ok"

before_build:
  - cmd: '%QTDIR%\bin\qtenv2.bat'
  - cmd: '"%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ENV_MSVC_PLATFORM%'

build_script:
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  - cmd: qmake %APPVEYOR_BUILD_FOLDER%/maltester.pro -r "CONFIG+=%configuration%"
  - cmd: nmake.exe
  - cmd: "%BUILD_DIR%/src/tests/release/tests.exe"
  - cmd: SET PATH=%BUILD_DIR%\src\app\release;%DOWNLOAD_DIR%\asn1scc;%PATH%
  - cmd: SET CRAMTESTS=
  - cmd: FOR %%t IN ("%APPVEYOR_BUILD_FOLDER%\tests\*.t") DO CALL SET CRAMTESTS= %%CRAMTESTS%% %%t
  - cmd: python -m cram -v -E -y --shell="C:\Program Files\Git\bin\sh.exe" %CRAMTESTS%

after_build:
  - cmd: mkdir %DIST_DIR%\asn1scc-MalTester
  - cmd: cd %DIST_DIR%\asn1scc-MalTester
  - cmd: copy /Y %BUILD_DIR%\src\app\release\*.exe .
  - cmd: copy /Y %APPVEYOR_BUILD_FOLDER%\LICENSE .
  - cmd: copy /Y %APPVEYOR_BUILD_FOLDER%\README.md .
  - cmd: copy /Y %QTDIR%\bin\Qt5Core.dll .
  - cmd: cd %DIST_DIR%
  - cmd: 7z a %APPVEYOR_BUILD_FOLDER%\asn1scc-MalTester-%APPVEYOR_REPO_TAG_NAME%-win.zip *

artifacts:
  - path: 'asn1scc-MalTester-*.zip'
    name: zip_archive

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: a0s0itv384dggr5rZVAK34HpB4dOBbG7LBZusrbtcK0KWbvkh89AZfGrwQXDAvB2
  artifact: zip_archive
  on:
    appveyor_repo_tag: true
