language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: linux
    compiler: clang
  allow_failures:
  - os: osx
  fast_finish: true

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - qt510-meta-minimal
    - qt510tools
    - python-setuptools
    - python-pip

install:
  - travis/install.sh

script:
  - travis/script.sh